ALGORITHMS_FOLDER = '/algorithms'
ALREADY_IN_SHINY_APP = "Your are already in a Shiny App Directory"
DATA_FOLDER = '/algorithms' + '/data'
GIVE_ALGORITHM_NAME = "Please provide an Algorithm name"
INCLUDE_R_FILES_IN_ALGORITHMS = "Please include only .R files in the algorithms folder\n"
INCORRECT_FOLDER_STRUCTURE = "You are not following the correct folder structure \n"
SHINY_STATE_FILE = '/.shiny' + '/.shiny-state'
SHINY_STATE_FOLDER = '/.shiny'
NAME_OF_SHINY_APP = "app_name"
NO_ALGORITHMS_FOLDER = "Algorithms folder does not exist. Please first create it"
NO_SHINY_STATE_FILE = ".shiny-state file does not exists.Please create it.\n"
NO_R_FILES_IN_DATA_FOLDER = "Please do not include .R files in the data folder\n"
NOT_IN_SHINY_APP = "You are not in your Shiny App Directory"
NOT_IN_SHINY_APP_OR_NO_STATE_FILE = "You are not in your Shiny App Directory or The state file does not exists \n"
SAME_ALGORITHM_EXISTS = "You Already have an Algorithm with the same name"
SAME_NAME_APP_EXISTS = "You already have a Shiny App with the same name"
TESTS_DATA_FODLER = '/tests' + '/test_data'
TESTS_FOLDER = '/tests'
